"""
LLM evaluator prompt on interaction logs.
"""

from __future__ import annotations


LLM_EVALUATOR_PROMPT = """Please evaluate the following interactions of an agent with a recommender system, and determine whether it is generated by a Large Language Model (LLM) AI or a real human.

[INTERACTION LOGS]
{interaction_logs}

Please rate on a scale of 1 to 5, with 1 being most like an AI and 5 being most like a human.

Output format (exactly 2 lines, no extra text):
RATING: <integer 1-5>
REASON: <2-4 sentences>
"""
